CREATE TABLE IF NOT EXISTS clients(
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS phones(
	id SERIAL PRIMARY KEY,
	client_id INTEGER NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
	phone VARCHAR(30) NOT NULL
);