FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y g++ build-essential vim nano

WORKDIR /app

COPY HelloDocker.cpp /app/

RUN g++ -o HelloDocker HelloDocker.cpp

CMD ["./HelloDocker"]   